{{- if and .Values.enabled .Values.exporter.enabled .Values.exporter.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "pgbouncer.fullname" . }}-exporter
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pgbouncer.labels" . | nindent 4 }}
    {{- with .Values.exporter.podMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.exporter.podMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "pgbouncer.selectorLabels" . | nindent 6 }}
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.exporter.podMonitor.interval }}
      scrapeTimeout: {{ .Values.exporter.podMonitor.scrapeTimeout }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}
